#!/bin/bash

set -e # exit on error

source $CONCOURSE_RESOURCES/shared

metadata=$($cmd)

jq -n --argjson metadata "$metadata" --argjson version "$VERSION" '{"version":$version,"metadata":$metadata}' 3>&1