#!/bin/bash

source $CONCOURSE_RESOURCES/shared

# generate timestamp bases version, which will automatically trigger the "in" script
jq -n --argjson  version "$VERSION_OUT" '{"version":$version}' 3>&1