#!/bin/bash

cd $1 # enter the build directory

function expand_param {
    if [ -z "$1" ]; then 
        return
    fi

    res=$(jq -er '.file' 2> /dev/null <<< $1)
    if [ "$?" -eq "0" ]; then
        cat "$res"
        return
    fi
    
    echo "$1"
}

input=$(cat) # read stdin JSON provided by Concourse

# Set parameters from the job level
OVEROPS_URL=$(jq -r '.params.overops_url | values' <<< $input)
OVEROPS_SID=$(jq -r '.params.overops_sid | values' <<< $input)
OVEROPS_API_KEY=$(jq -r '.params.overops_api_key | values' <<< $input)
OVEROPS_APPLICATION_NAME=$(jq -r '.params.application_name | values' <<< $input)
OVEROPS_DEPLOYMENT_NAME=$(jq -r '.params.deployment_name | values' <<< $input)
OVEROPS_SERVICE_ID=$(jq -r '.params.service_id | values' <<< $input)
OVEROPS_REGEX_FILTER=$(jq -r '.params.regex_filter | values' <<< $input)
OVEROPS_MARK_UNSTABLE=$(jq -r '.params.mark_unstable | values' <<< $input)
OVEROPS_PRINT_TOP_ISSUES=$(jq -r '.params.print_top_issues | values' <<< $input)
OVEROPS_NEW_EVENTS=$(jq -r '.params.new_events | values' <<< $input)
OVEROPS_RESURFACED_ERRORS=$(jq -r '.params.resurfaced_errors | values' <<< $input)
OVEROPS_MAX_ERROR_VOLUME=$(jq -r '.params.max_error_volume | values' <<< $input)
OVEROPS_MAX_UNIQUE_ERRORS=$(jq -r '.params.max_unique_errors | values' <<< $input)
OVEROPS_CRITICAL_EXCEPTION_TYPES=$(jq -r '.params.critical_exception_types | values' <<< $input)
OVEROPS_ACTIVE_TIMESPAN=$(jq -r '.params.active_timespan | values' <<< $input)
OVEROPS_BASE_LINE_TIMESPAN=$(jq -r '.params.baseline_timespan | values' <<< $input)
OVEROPS_MIN_VOLUME_THRESHOLD=$(jq -r '.params.min_volume_threshold | values' <<< $input)
OVEROPS_MIN_ERROR_RATE_THRESHOLD=$(jq -r '.params.min_error_rate_threshold | values' <<< $input)
OVEROPS_REGRESSION_DELTA=$(jq -r '.params.regression_delta | values' <<< $input)
OVEROPS_CRITICAL_REGRESSION_DELTA=$(jq -r '.params.critical_regression_delta | values' <<< $input)
OVEROPS_APPLY_SEASONALITY=$(jq -r '.params.apply_seasonality | values' <<< $input)
OVEROPS_DEBUG=$(jq -r '.params.debug | values' <<< $input)

# Set global level parameters, if the local level ones where not set
OVEROPS_URL=$(expand_param "${OVEROPS_URL:-$(jq -r '.source.overops_url | values' <<< $input)}")
OVEROPS_SID=$(expand_param "${OVEROPS_SID:-$(jq -r '.source.overops_sid | values' <<< $input)}")
OVEROPS_API_KEY=$(expand_param "${OVEROPS_API_KEY:-$(jq -r '.source.overops_api_key | values' <<< $input)}")
OVEROPS_APPLICATION_NAME=$(expand_param "${OVEROPS_APPLICATION_NAME:-$(jq -r '.source.application_name | values' <<< $input)}")
OVEROPS_DEPLOYMENT_NAME=$(expand_param "${OVEROPS_DEPLOYMENT_NAME:-$(jq -r '.source.deployment_name | values' <<< $input)}")
OVEROPS_SERVICE_ID=$(expand_param "${OVEROPS_SERVICE_ID:-$(jq -r '.source.service_id | values' <<< $input)}")
OVEROPS_REGEX_FILTER=$(expand_param "${OVEROPS_REGEX_FILTER:-$(jq -r '.source.regex_filter | values' <<< $input)}")
OVEROPS_MARK_UNSTABLE=$(expand_param "${OVEROPS_MARK_UNSTABLE:-$(jq -r '.source.mark_unstable | values' <<< $input)}")
OVEROPS_PRINT_TOP_ISSUES=$(expand_param "${OVEROPS_PRINT_TOP_ISSUES:-$(jq -r '.source.print_top_issues | values' <<< $input)}")
OVEROPS_NEW_EVENTS=$(expand_param "${OVEROPS_NEW_EVENTS:-$(jq -r '.source.new_events | values' <<< $input)}")
OVEROPS_RESURFACED_ERRORS=$(expand_param "${OVEROPS_RESURFACED_ERRORS:-$(jq -r '.source.resurfaced_errors | values' <<< $input)}")
OVEROPS_MAX_ERROR_VOLUME=$(expand_param "${OVEROPS_MAX_ERROR_VOLUME:-$(jq -r '.source.max_error_volume | values' <<< $input)}")
OVEROPS_MAX_UNIQUE_ERRORS=$(expand_param "${OVEROPS_MAX_UNIQUE_ERRORS:-$(jq -r '.source.max_unique_errors | values' <<< $input)}")
OVEROPS_CRITICAL_EXCEPTION_TYPES=$(expand_param "${OVEROPS_CRITICAL_EXCEPTION_TYPES:-$(jq -r '.source.critical_exception_types | values' <<< $input)}")
OVEROPS_ACTIVE_TIMESPAN=$(expand_param "${OVEROPS_ACTIVE_TIMESPAN:-$(jq -r '.source.active_timespan | values' <<< $input)}")
OVEROPS_BASE_LINE_TIMESPAN=$(expand_param "${OVEROPS_BASE_LINE_TIMESPAN:-$(jq -r '.source.baseline_timespan | values' <<< $input)}")
OVEROPS_MIN_VOLUME_THRESHOLD=$(expand_param "${OVEROPS_MIN_VOLUME_THRESHOLD:-$(jq -r '.source.min_volume_threshold | values' <<< $input)}")
OVEROPS_MIN_ERROR_RATE_THRESHOLD=$(expand_param "${OVEROPS_MIN_ERROR_RATE_THRESHOLD:-$(jq -r '.source.min_error_rate_threshold | values' <<< $input)}")
OVEROPS_REGRESSION_DELTA=$(expand_param "${OVEROPS_REGRESSION_DELTA:-$(jq -r '.source.regression_delta | values' <<< $input)}")
OVEROPS_CRITICAL_REGRESSION_DELTA=$(expand_param "${OVEROPS_CRITICAL_REGRESSION_DELTA:-$(jq -r '.source.critical_regression_delta | values' <<< $input)}")
OVEROPS_APPLY_SEASONALITY=$(expand_param "${OVEROPS_APPLY_SEASONALITY:-$(jq -r '.source.apply_seasonality | values' <<< $input)}")
OVEROPS_DEBUG=$(expand_param "${OVEROPS_DEBUG:-$(jq -r '.source.debug | values' <<< $input)}")

# Set version to be used in main script (in, out, check)
VERSION_IN='{}'
if [ -n "$OVEROPS_DEPLOYMENT_NAME" ]; then
  VERSION_IN="{\"deployment\": \"$OVEROPS_DEPLOYMENT_NAME\"}"
fi

# prepare the execution cmd adding the cli parameter only if it was provided as Concourse job parameter
cmd="""
java -jar /artifact/concourse-overops.jar \
    ${OVEROPS_URL:+--overOpsURL=$OVEROPS_URL} \
    ${OVEROPS_SID:+--overOpsSID=$OVEROPS_SID} \
    ${OVEROPS_API_KEY:+--overOpsAPIKey=$OVEROPS_API_KEY} \
    ${OVEROPS_APPLICATION_NAME:+--applicationName=$OVEROPS_APPLICATION_NAME} \
    ${OVEROPS_DEPLOYMENT_NAME:+--deploymentName=$OVEROPS_DEPLOYMENT_NAME} \
    ${OVEROPS_SERVICE_ID:+--serviceId=$OVEROPS_SERVICE_ID} \
    ${OVEROPS_REGEX_FILTER:+--regexFilter=$OVEROPS_REGEX_FILTER} \
    ${OVEROPS_MARK_UNSTABLE:+--markUnstable=$OVEROPS_MARK_UNSTABLE} \
    ${OVEROPS_PRINT_TOP_ISSUES:+--printTopIssues=$OVEROPS_PRINT_TOP_ISSUES} \
    ${OVEROPS_NEW_EVENTS:+--newEvents=$OVEROPS_NEW_EVENTS} \
    ${OVEROPS_RESURFACED_ERRORS:+--resurfacedErrors=$OVEROPS_RESURFACED_ERRORS} \
    ${OVEROPS_MAX_ERROR_VOLUME:+--maxErrorVolume=$OVEROPS_MAX_ERROR_VOLUME} \
    ${OVEROPS_MAX_UNIQUE_ERRORS:+--maxUniqueErrors=$OVEROPS_MAX_UNIQUE_ERRORS} \
    ${OVEROPS_CRITICAL_EXCEPTION_TYPES:+--criticalExceptionTypes=$OVEROPS_CRITICAL_EXCEPTION_TYPES} \
    ${OVEROPS_ACTIVE_TIMESPAN:+--activeTimespan=$OVEROPS_ACTIVE_TIMESPAN} \
    ${OVEROPS_BASE_LINE_TIMESPAN:+--baselineTimespan=$OVEROPS_BASE_LINE_TIMESPAN} \
    ${OVEROPS_MIN_VOLUME_THRESHOLD:+--minVolumeThreshold=$OVEROPS_MIN_VOLUME_THRESHOLD} \
    ${OVEROPS_MIN_ERROR_RATE_THRESHOLD:+--minErrorRateThreshold=$OVEROPS_MIN_ERROR_RATE_THRESHOLD} \
    ${OVEROPS_REGRESSION_DELTA:+--regressionDelta=$OVEROPS_REGRESSION_DELTA} \
    ${OVEROPS_CRITICAL_REGRESSION_DELTA:+--criticalRegressionDelta=$OVEROPS_CRITICAL_REGRESSION_DELTA} \
    ${OVEROPS_APPLY_SEASONALITY:+--applySeasonality=$OVEROPS_APPLY_SEASONALITY} \
    ${OVEROPS_DEBUG:+--debug=$OVEROPS_DEBUG} \
    ${OVEROPS_CHECK:+--checkVersion=$OVEROPS_CHECK}
"""

if [ $OVEROPS_DEBUG == "true" ]; then
    1>&2 find .
    1>&2 echo ${input//$OVEROPS_API_KEY/***}
    # print the executed command without exposing the API Key
    1>&2 echo ${cmd//$OVEROPS_API_KEY/***}
fi
